#Introduction to TensorFlow

# 📘 TensorFlow Basics

TensorFlow is a powerful open-source library developed by Google for deep learning and numerical computation. It uses dataflow graphs and automatic differentiation to perform optimized computations.

Let's get started by learning how to use Tensors, which are the fundamental building blocks of TensorFlow.


##Installing and Importing TensorFlow

In [1]:
!pip install tensorflow -q
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.21.0


## 📦 Tensors

Tensors are multi-dimensional arrays (like NumPy arrays). TensorFlow supports scalar (0D), vector (1D), matrix (2D), and higher dimensional tensors.

Let's see how to create and inspect them.


##Tensor Creation and Attributes

In [2]:
# Scalar
scalar = tf.constant(7)
print("Scalar:", scalar)

# Vector
vector = tf.constant([1.0, 2.0, 3.0])
print("Vector:", vector)

# Matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# Check shape and dtype
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)


Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Shape: (2, 2)
Data Type: <dtype: 'int32'>


## ➕ Tensor Operations

TensorFlow supports element-wise operations like addition, multiplication, matrix multiplication, etc.


##Tensor Arithmetic

In [3]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Addition
print("Addition:\n", tf.add(a, b))

# Multiplication (element-wise)
print("Element-wise Multiplication:\n", tf.multiply(a, b))

# Matrix multiplication
print("Matrix Multiplication:\n", tf.matmul(a, b))


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# 🏗️ Building a Neural Network with TensorFlow (Keras)

We'll use `tf.keras`, a high-level API for building and training models. Let's train a simple neural network to classify digits using the MNIST dataset.


##Load Dataset and Normalize

In [4]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize to [0, 1]
x_train, x_test = x_train / 255.0, x_test / 255.0


In [5]:
print(x_train.shape)

(60000, 28, 28)


##Define a Model


In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),  # Input layer
    tf.keras.layers.Dense(128, activation='relu'),  # Hidden layer
    tf.keras.layers.Dense(10, activation='softmax') # Output layer
])


c:\Users\ZEENAT MUSTAFA\.conda\envs\ai-bootcamp\lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


##Compile and Train

In [7]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9257 - loss: 0.2574
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9653 - loss: 0.1149
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9764 - loss: 0.0784
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9817 - loss: 0.0587
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9859 - loss: 0.0456


##Evaluate the Model

In [8]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print("\nTest Accuracy:", test_acc)


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9786 - loss: 0.0684

Test Accuracy: 0.978600025177002


#1. Understand the Basic Syntax and Operations (PyTorch)

# Introduction to PyTorch
## 🔥 PyTorch Basics

PyTorch is a popular open-source deep learning library developed by Facebook AI. It provides flexibility and speed through dynamic computation graphs and strong GPU support.

In this section, we'll start by exploring how PyTorch handles tensors and automatic differentiation.


##Installing and Importing PyTorch

In [9]:
# If you're in a notebook or Colab
!pip install torch -q
import torch
print("PyTorch version:", torch.__version__)


PyTorch version: 2.13.0+cpu


##Creating and Inspecting Tensors
## 📦 Tensors in PyTorch

Tensors are multidimensional arrays, just like in NumPy. They're the building blocks of PyTorch and support operations like addition, multiplication, reshaping, etc.


##Tensor Creation and Properties

In [10]:
# Scalar
scalar = torch.tensor(5)
print("Scalar:", scalar)

# Vector
vector = torch.tensor([1.0, 2.0, 3.0])
print("Vector:", vector)

# Matrix
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Matrix:\n", matrix)

# Shape and data type
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)


Scalar: tensor(5)
Vector: tensor([1., 2., 3.])
Matrix:
 tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])
Data Type: torch.float32


## ➕ Tensor Operations

PyTorch supports common element-wise operations as well as matrix multiplication, reshaping, and broadcasting.


##Tensor Arithmetic

In [11]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Addition
print("Addition:\n", a + b)

# Element-wise multiplication
print("Element-wise Multiplication:\n", a * b)

# Matrix multiplication
print("Matrix Multiplication:\n", torch.matmul(a, b))


Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


# 🏗️ Building a Neural Network with PyTorch

Now let's build a simple neural network to classify digits from the MNIST dataset using `torch.nn` and `torch.optim`.


##Load and Normalize MNIST Dataset

In [13]:
!pip install torchvision -q

In [14]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Transform: Normalize to [0, 1]
transform = transforms.ToTensor()

train_data = datasets.MNIST(root='data', train=True, download=True, transform=transform)
test_data = datasets.MNIST(root='data', train=False, download=True, transform=transform)

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)


100.0%
100.0%
100.0%
100.0%


##Define Neural Network

In [15]:
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(x.shape[0], -1)  # Flatten
        x = F.relu(self.fc1(x))
        return F.log_softmax(self.fc2(x), dim=1)

model = SimpleNN()


##Define Loss and Optimizer

In [16]:
import torch.optim as optim

criterion = nn.NLLLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


##Train the Model

In [17]:
epochs = 3
for epoch in range(epochs):
    for images, labels in train_loader:
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


Epoch 1, Loss: 0.2508
Epoch 2, Loss: 0.0838
Epoch 3, Loss: 0.0288


##Evaluate Accuracy

In [18]:
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Test Accuracy: {correct / total * 100:.2f}%")


Test Accuracy: 96.90%


#3. Compare Similarities and Differences with TensorFlow


# PyTorch vs TensorFlow: Quick Comparison

| Feature                | PyTorch                               | TensorFlow                           |
|------------------------|----------------------------------------|--------------------------------------|
| Execution Mode         | Eager (Dynamic)                        | Eager (Static with option for Graph) |
| High-Level API         | `torch.nn`, `torch.optim`              | `tf.keras`                           |
| Dataset Loader         | `DataLoader`                           | `tf.data.Dataset`                    |
| Training Loop Style    | Mostly manual                          | `model.fit()` or manual              |
| Model Saving           | `torch.save()`                         | `model.save()` or `SavedModel`       |
| Visualization Tool     | TensorBoard (via `torch.utils.tensorboard`) | TensorBoard                    |
| Autograd Support       | Built-in via `autograd`                | `tf.GradientTape()`                  |

Both libraries are capable of building state-of-the-art models. Your choice depends on project needs and comfort with syntax.


--------------------------------------------------------------------------------

#Activity

Create two custom models, one with Tensorflow and the other with Pytorch.
The models should have

###  Model Architecture (Same for Both Frameworks)

| Layer Type         | Configuration                      |
|--------------------|-------------------------------------|
| Input Layer        | Flatten (28×28 → 784)              |
| Dense Layer 1      | 256 units, ReLU                    |
| Dropout Layer      | 30% (rate = 0.3)                   |
| Dense Layer 2      | 128 units, Tanh                    |
| Output Layer       | 10 units, Softmax (TF) / LogSoftmax (PT) |

###  Instructions

- Implement this architecture using `tf.keras.Sequential` in TensorFlow.
- Implement the same architecture using `torch.nn.Module` in PyTorch.
- Train both models for **5 epochs** using the **Adam optimizer** and an appropriate classification loss.
- Evaluate accuracy on the MNIST test set.


In [ ]:
# TensorFlow / Keras Version
import tensorflow as tf

# Build the model
tf_model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),        # Input: 28x28 -> 784
    tf.keras.layers.Dense(256, activation='relu'),         # Dense Layer 1: 256 units, ReLU
    tf.keras.layers.Dropout(0.3),                          # Dropout: 30%
    tf.keras.layers.Dense(128, activation='tanh'),         # Dense Layer 2: 128 units, Tanh
    tf.keras.layers.Dense(10, activation='softmax')        # Output: 10 units, Softmax
])

# Compile
tf_model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

# Train
tf_model.fit(x_train, y_train, epochs=5)

# Evaluate
test_loss, test_acc = tf_model.evaluate(x_test, y_test)
print("\nTensorFlow Test Accuracy:", test_acc)

Epoch 1/5


c:\Users\ZEENAT MUSTAFA\.conda\envs\ai-bootcamp\lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9271 - loss: 0.2408
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9634 - loss: 0.1177
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9707 - loss: 0.0933
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9750 - loss: 0.0773
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9774 - loss: 0.0694
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9772 - loss: 0.0732

TensorFlow Test Accuracy: 0.9771999716758728


In [20]:
# PyTorch Version
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class CustomNN(nn.Module):
    def __init__(self):
        super(CustomNN, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 256)   # Dense Layer 1: 256 units
        self.dropout = nn.Dropout(0.3)        # Dropout: 30%
        self.fc2 = nn.Linear(256, 128)        # Dense Layer 2: 128 units
        self.fc3 = nn.Linear(128, 10)         # Output: 10 units

    def forward(self, x):
        x = x.view(x.shape[0], -1)            # Flatten: 28x28 -> 784
        x = F.relu(self.fc1(x))               # ReLU activation
        x = self.dropout(x)                   # Apply dropout
        x = F.tanh(self.fc2(x))               # Tanh activation
        return F.log_softmax(self.fc3(x), dim=1)  # LogSoftmax output

pt_model = CustomNN()

criterion = nn.NLLLoss()
optimizer = optim.Adam(pt_model.parameters(), lr=0.001)

# Train
epochs = 5
for epoch in range(epochs):
    for images, labels in train_loader:
        optimizer.zero_grad()
        output = pt_model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

# Evaluate
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        outputs = pt_model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"\nPyTorch Test Accuracy: {correct / total * 100:.2f}%")

Epoch 1, Loss: 0.0634
Epoch 2, Loss: 0.0930
Epoch 3, Loss: 0.0822
Epoch 4, Loss: 0.0044
Epoch 5, Loss: 0.0626

PyTorch Test Accuracy: 97.21%
